// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1-bdz3g-2iRpr_qE5cu_YagUR4oxBWek',
    appId: '1:788635581157:web:453ecef2da6363d5e2320c',
    messagingSenderId: '788635581157',
    projectId: 'call-me-98459',
    authDomain: 'call-me-98459.firebaseapp.com',
    storageBucket: 'call-me-98459.appspot.com',
    measurementId: 'G-SF86Z0Z77Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiKPNrH_E-mkjV48TmveoM7VfR3mSMKfM',
    appId: '1:788635581157:android:74bb16e4de341a23e2320c',
    messagingSenderId: '788635581157',
    projectId: 'call-me-98459',
    storageBucket: 'call-me-98459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvj3drnJijnXic1sbvB2Ki8FQbtxDj578',
    appId: '1:788635581157:ios:5011309f09a63a4ce2320c',
    messagingSenderId: '788635581157',
    projectId: 'call-me-98459',
    storageBucket: 'call-me-98459.appspot.com',
    iosClientId: '788635581157-p5e55127mrl9l51b6domm2qfolnlm5ak.apps.googleusercontent.com',
    iosBundleId: 'com.example.call',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvj3drnJijnXic1sbvB2Ki8FQbtxDj578',
    appId: '1:788635581157:ios:b83b63b025407f6ee2320c',
    messagingSenderId: '788635581157',
    projectId: 'call-me-98459',
    storageBucket: 'call-me-98459.appspot.com',
    iosClientId: '788635581157-cbqd92doodmhnns7lce593sfans9udup.apps.googleusercontent.com',
    iosBundleId: 'com.example.call.RunnerTests',
  );
}
